version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "11:00"
      timezone: Pacific/Auckland
    ignore:
      - dependency-name: "github.com/aws/aws-sdk-go*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 10
    reviewers:
      - JasperLabs/backend

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
      timezone: Pacific/Auckland
    open-pull-requests-limit: 10
    reviewers:
      - JasperLabs/backend
